name:                NComplement
version:             0.1.0.0
github:              "ambroslins/NComplement"
license:             BSD3
author:              "Ambros Lins"
maintainer:          "ambros.lins@gmail.com"
copyright:           "2020 Ambros Lisn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NComplement#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec >= 9.0.0
- parser-combinators
- replace-megaparsec
- mtl
- tardis
- containers
- text
- filepath
- prettyprinter

default-extensions:
  - LambdaCase
  - OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  NComplement:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - NComplement

tests:
  NComplement-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - NComplement
    - hspec
    - hspec-megaparsec >= 2.2.0
    - QuickCheck
