name:                NCompiler
version:             0.1.0.0
github:              "ambroslins/NCompiler"
license:             BSD3
author:              "Ambros Lins"
maintainer:          "ambros.lins@gmail.com"
copyright:           "2020 Ambros Lisn"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NCompiler#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- replace-megaparsec
- mtl
- tardis
- containers
- text

default-extensions:
  - LambdaCase
  - OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -Wall

executables:
  NCompiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - NCompiler

tests:
  NCompiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NCompiler
